spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    virtual-host: /
    publisher-confirm-type: simple
    publisher-returns: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.web3j.protocol: INFO
